[tool.poetry]
name = "elegy"
version = "0.1.0"
description = ""
authors = ["Cristian Garcia <cgarcia.e88@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
jaxlib = "^0.1.50"
dm-haiku = "^0.0.1"
numpy = "^1.19.0"
pytest = "^5.4.3"
pytest-sugar = "^0.9.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mkdocs = "^1.1.2"
mkdocs-material = "^5.4.0"
mkdocstrings = "^0.12.0"
black = {version = "^19.10b0", allow-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
